# NOTE: Custom image specification for freebsd is required until new version of cross is released.
# Also we'll have to use a custom image until https://github.com/rust-embedded/cross/pull/582 is
# merged and released on Docker Hub.
[target.x86_64-unknown-freebsd]
image = "svenstaro/cross-x86_64-unknown-freebsd"
